### ISSUE TITLE
请问该工具支持中文吗？

### ISSUE THREAD

**Issue by chk4991** [OFA-Sys/InsTag#2]

**Comment by yucc-leon** [comment]
试了demo提示不支持中文，但输入中文会以英文结果返回

**Comment by GanjinZero** [comment]
https://modelscope.cn/models/lukeminglkm/instagger_qwen1_8B/summary

**Comment by claudegpt** [comment]
> https://modelscope.cn/models/lukeminglkm/instagger_qwen1_8B/summary

对应的prompt和之前的InsTagger是一致的吗？
